# Generated by Django 2.2 on 2019-04-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='language',
            name='folder',
            field=models.ManyToManyField(blank=True, null=True, to='core.Folder'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='source_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='folder',
            field=models.ManyToManyField(blank=True, null=True, related_name='users_folder', to='core.Folder'),
        ),
    ]
