# Generated by Django 2.2 on 2019-04-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190403_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='snippets',
            field=models.ManyToManyField(blank=True, null=True, to='core.Snippet'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='title',
            field=models.CharField(max_length=35, unique=True),
        ),
    ]
