# Generated by Django 2.2 on 2019-04-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190404_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='category',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='languages',
        ),
        migrations.AddField(
            model_name='snippet',
            name='language',
            field=models.CharField(choices=[('html', 'HTML'), ('css', 'CSS'), ('js', 'Javascript'), ('bash', 'Bash'), ('basic', 'Basic'), ('c', 'C'), ('csharp', 'C#'), ('cpp', 'C++'), ('coffee', 'CoffeeScript'), ('clojure', 'Clojure'), ('docker', 'Docker'), ('elixir', 'Elixir'), ('fsharp', 'F#'), ('git', 'Git'), ('go', 'Go'), ('graphql', 'GraphQL'), ('java', 'Java'), ('json', 'JSON'), ('monkey', 'Monkey'), ('objectivec', 'Objective-C'), ('pascal', 'Pascal'), ('perl', 'Perl'), ('php', 'PHP'), ('py', 'Python'), ('jsx', 'React JSX'), ('ruby', 'Ruby'), ('rust', 'Rust'), ('sql', 'SQL'), ('swift', 'Swift'), ('ts', 'typescript'), ('yml', 'YAML')], default=None, max_length=420),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
