# Generated by Django 2.2.1 on 2019-05-23 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190522_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='slug',
        ),
    ]
