# Generated by Django 2.2.1 on 2019-05-23 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_snippet_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='post_content',
            field=models.TextField(max_length=15000),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
