# Generated by Django 2.2.1 on 2019-05-28 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190523_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='post_content',
            new_name='content',
        ),
    ]
